### ISSUE TITLE
Validator currently broken

### ISSUE THREAD

**Issue by cunei** [sbt/sbt-standalone-build#11]
The online validator is currently broken due to two separate issues. One, on occasion there will be a Null Pointer Exception in at sbt.internal.util.StringTypeTag$.typeToString(StringTypeTag.scala:27); this is non-deterministic. The other is a failure to resolve okhttp; this seems to be related to a weird interaction between Gigahorse and the current configuration of proxy-ch.lightbend.com; I'm working on this now.

**Comment by cunei** [comment]
A third issue turned out to be dbuild failing while publishing sbt-io in Jenkins, with the message:
```
[sbt212-io] Publishing: io
[sbt212-io] [error] java.lang.RuntimeException: bintrayVcsUrl not defined. assign this with bintrayVcsUrl := Some("git@github.com:you/your-repo.git")
[sbt212-io] [error]   at scala.sys.package$.error(package.scala:27)
[sbt212-io] [error]   at bintray.BintrayPlugin$.$anonfun$ensurePackageTask$2(BintrayPlugin.scala:156)
[sbt212-io] [error]   at scala.Option.getOrElse(Option.scala:121)
[sbt212-io] [error]   at bintray.BintrayPlugin$.$anonfun$ensurePackageTask$1(BintrayPlugin.scala:156)
[sbt212-io] [error]   at bintray.BintrayPlugin$.$anonfun$ensurePackageTask$1$adapted(BintrayPlugin.scala:154)
[sbt212-io] [error]   at scala.Function1.$anonfun$compose$1(Function1.scala:44)
```
I spent quite a bit of time trying to understand the reason, since the same build would work fine on my own machine. It would also work fine on the same machine, with the same account that runs the Jenkins tasks, even with the exact same environment. Eventually, I realized that the Jenkins job was named "sbt validator", with a whitespace. That apparently confuses sbt-bintray to some degree; I obtained the same error message also outside of dbuild if the build path contains whitespaces.
The Jenkins job has been renamed, and this error vanished.

**Comment by dwijnand** [comment]
> Eventually, I realized that the Jenkins job was named "sbt validator", with a whitespace.

(╯°□°）╯︵ ┻━┻

Nice find.. If you find a minimised reproduction we can try and fix it in sbt-bintray.

**Comment by cunei** [comment]
The `typeToString` NPE seems not to occur with 1.0.1. The okhttp failure is related to Gigahorse; the dbuild file is now using a slightly tweaked version of sbt 1.0.1 in which Gigahorse is disabled, so the validator is operating normally again. Closing.
