### ISSUE TITLE
Guess the branches to 1.0.x

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt-standalone-build#19]
### steps

1. Send a PR to Zinc targeting 1.0.x branch.

### problems

The bot creates a link, guessing all branches defaulting to 1.x.

![jenkins](https://user-images.githubusercontent.com/184683/33229335-da03b4c2-d19a-11e7-8148-8cd96914afd9.png)

### expectation

When the target is 1.0.x, the other modules should also use 1.0.x branch.

**Comment by cunei** [comment]
It seems this information is not available via the webhook request directly. For example, this pull request was opened against 1.1.x:
https://github.com/sbt/librarymanagement/pull/204
But "1.1.x" does not appear anywhere in the corresponding webhook request:
https://jenkins.scala-sbt.org:8592/job/GitHub%20PR%20responder/1577/console
I'll see if there is a roundabout way to get to it, by using the GitHub API to query the pull request

**Comment by cunei** [comment]
This is implemented now. Closing
