### ISSUE TITLE
Not a valid project ID: vscodePlugin

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt-standalone-build#20]
### steps

1. Use 1.0.x branch for sbt/sbt during validation.

### problems

```
[sbt212] [error] Not a valid project ID: vscodePlugin (similar: scriptedPluginProj)
[sbt212] [error] project vscodePlugin
[sbt212] [error]                     ^
```

### expectation

vscodePlugin is not included for 1.0.x branch, or do something to trick the build.

**Comment by cunei** [comment]
This has been solved a while back; closing.

**Comment by amixpal** [comment]
What was the solution?

**Comment by cunei** [comment]
@amixpal The 1.0.x branch is no longer active, the validator tests 1.1.x and 1.x (aka 1.2) at this time. https://jenkins.scala-sbt.org:8592/job/sbt-validator/
