### ISSUE TITLE
Failure in the 1.x nightly (2018-05-09)

### ISSUE THREAD

**Issue by cunei** [sbt/sbt-standalone-build#25]
```
Eval.scala:547:14: object JavaMilli is not a member of package sbt.io
[sbt212] [error]       sbt.io.JavaMilli.getModifiedTime(f.getPath)
```
It is the result of https://github.com/sbt/sbt/commit/8781c16cbb8695a14a11b3372eaca4971e7bf56b#diff-e2a9beabb534ced1b3c3b9201843f38dL518, but https://github.com/sbt/io/pull/139
(specifically https://github.com/sbt/io/pull/139/commits/d03bb126234305d4332dffc9fd54c06f4acb5845) is not in io/1.x. Incidentally, there was also a later (still incomplete) change planned on that code in https://github.com/sbt/sbt/pull/4094, https://github.com/sbt/sbt/issues/4116.

**Comment by eed3si9n** [comment]
I am compile with all sources now, so this is now fixed?
